version: '3.7'

services:
  etherscan-monitoring-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  etherscan-monitoring-backend-pg:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '15432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
